# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Site settings
permalink: /:title.html
exclude: ["Makefile", "README.md", "./_/", "CNAME", "node_modules"]
sass:
  style: compressed

# Site info
url: http://jevzelenkov.com/til
title: Today I Learned

# Google analytics
analytics:
  hostname: jevzelenkov.com
  id: "UA-62803891-1"

# Collections
collections:
  - authors

# Default variables
defaults:
  - scope:
      path: ""
    values:
      layout: "article"
      tags: []
      author: Jev Zelenkov
